### ISSUE TITLE
冯宇静

### ISSUE THREAD

**Issue by FYJvin** [android-nuc/17-C-Train#61]
...c
#include<stdio.h>
int main()
{
	int n,i;
	char a[100];
	printf("请输入字符串的长度 :");
	scanf("%d\n",&n);
    gets(a);
	printf("%s\n",a);
	a[0] = a[0]-32;
	printf("%c",a[0]);
	for(i=2;i<n;i++)
	{
		if(a[i-1]==' ')
		{
			a[i] = a[i]-32;
			printf("%c",a[i]);
		}
		else
		{
			printf("%c",a[i]);
		}

	}
	return 0;
}

#include<stdio.h>
int main ()
{
    int  a[3];
    a[0] = 1;
    a[1] = 1;
    a[2] = 2;
    printf("输出一百以内的斐波那契数：\n%d\n%d\n%d",a[0],a[1],a[2]);
    for(;a[2]<=100;)
    {
    	a[2] = a[1]+a[0];
		a[0] = a[1];
		a[1] = a[2];
		if (a[2]<=100)
		printf("\n%d",a[2]);
	}
		return 0; 
    
}

#include<stdio.h>
int main()
{
	int a,b,m,n,i,j,p;
	printf("请输入菱形最短边到最长边的行数：");
	scanf("%d",&p);
	for(int i=1;i<=p;i++)
	{
		for(int a=1;a<=p-i;a++)
		{
			printf(" ");
		}
		for(int b=1;b<=2*i-1;b++)
		{
			printf("*");
		}
		printf("\n");
	}
	for(int j=p-1;j>=1;j--)
	{
		for(int m=p-1;m>=j;m--)
		{
			printf(" ");
		}
		for(int n=1;n<=2*j-1;n++)
		{
				printf("*");
		}
		printf("\n");
		
	 } 
	return 0;
	

#include<stdio.h>
int main()
{
	int a[100][100];
	int n,i,j,p;
	printf("请输入数组的阶数：");
	scanf("%d",&n);
	for(i=0;i<n;i++)
	{
		for(j=0;j<n;j++)
		{
			scanf("%d",&a[i][j]);
		}
	printf("\n");
	}
	printf("%d\n",a[0][0]);
	printf("%d\n",a[n-1][n-1]);
	p = a[0][0]+a[n-1][n-1];
	printf("%d\n",p);
	return 0;

} 

#include<stdio.h>
int main()
{
	int a[100][100],b[100][100];
	int c,d,e,m,i,j,p;
     p =0;
	printf("请分别输入两个矩阵的行列数：行，列，列");
	scanf("%d%d%d",&c,&d,&e);
	for(m=0;m<c;m++)
	{
		for(i=0;i<d;i++)
		{
			scanf("%d",&a[m][i]);
		}
	printf("\n");
	}
	for(i=0;i<d;i++)
	{
		for(j=0;j<e;j++)
		{
			scanf("%d",&b[i][j]);
		}
	printf("\n");
	}
    for(m = 0;m < c;m ++)
    {
	    for(j = 0;j < e;j ++)
	    {
		    for(i = 0;i < d;i ++)
		    {
		 	    p =  p + a[m][i] * b[i][j];
		 	    
		    } 
		    printf("%d ",p);
 	    }
 	printf("\n");
    }
	return 0;
}

#include<stdio.h>
int main()
{
	int n,i;
	n = 0;
	i = 1;
	for(i = 1;i<=9;i++)
	{
		n = n+(n+1)*2; 
	}
	printf("%d",n);
	return 0;
 } 

#include<stdio.h>
int main()
{
	int a[100];
	int n,i ,m,sum;
	sum = 0;
	printf("请输入数字长度：");
	scanf("%d",&n); 
	for(i=0;i<n;i++)
		{
			scanf("%d",a);
		}
	for(i = 0;i<n;i++)
	{
		if(a[i]!=0)
		{
			printf("%d",a[i]);
	    }
	    else
	    {
			sum = sum + 1;
	  
	    }
	   printf("%d",sum);
	   
	   
	   
	}
	for( m=1;m<=sum;m++)
	{
		printf('\0');
	}
	return 0;
 } 

#include<stdio.h>
int main()
{
	int m, n, i, j;
	static  int a[1000][1000];
	printf("请输入一个杨辉三角的行数：");
	scanf("%d",&n);
	for(i=0;i<n;i++)
	{
	
		for(j=0;j<=i;j++)
		{	
			if(i==j||j==0)
				a[i][j]=1;
			else
				a[i][j]=a[i-1][j-1]+a[i-1][j];
		//	printf("%d",a[i][j]);
		}
	//	printf("\n");
	}
	for(i=0;i<n-1;i++)
	{
		for(m=0;m<n-i;m++)
			printf(" ");
		for(j=0;j<=i;j++)
		{
			printf("%d",a[i][j]);
			printf(" ");
		}
		printf("\n");

	}
	return 0;

}
...c

**Comment by xmmmmmovo** [comment]
是

#### ```c

#### ```
吧
不是
···c
···
